<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\elor.jpg" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\elor.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VKUI.Avalonia\VKUI.csproj" />
  </ItemGroup>
</Project>
